spring:
  application:
    name: gira-user
  profiles:
#    default: dev
    default: local

  config:
#    import: configserver:http://172.31.42.150:8888
    import: configserver:http://localhost:8888
management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httpexchange, busrefresh




